# Site settings
name: Aman Ahmed
title: Aman Ahmed | Network Technician
description: an open minded programmer and a web designer
url: https://mannu.me/
baseurl: ''
email: aman@ctemplar.com
cover: https://mannu.me/img/og.png
logo: https://mannu.me/img/emojis/programmerboy.png
resume: https://mannu.me/resume.pdf
social:
  - title: email
    url: mailto:aman@ctemplar.com
  - title: twitter
    url: https://twitter.com/ma_nnu_me
  - title: codepen
    url: https://codepen.io/pokurt
  - title: github
    url: https://github.com/pokurt
  - title: telegram
    url: https://t.me/pokurt

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
